### PR TITLE
Added a method in Email to be able to set a format for the body

### PR DESCRIPTION
**Pull request by edurenye**
Pull request for #23

### CODE REVIEW

**Comment by edurenye** [comment]
I'll check the failing tests tomorrow.

**Comment by dpi** [comment]
The Travis CI script runs tests with the PHP builtin server -- its been all kinds of unpredictable. So long as it passes locally you should be A-OK.

~~Also... With every setter comes a getter. :)~~

**Comment by edurenye** [comment]
The tests passes locally.

**Comment by dpi** [comment]
Committed with minor changes to method order.

**Pull request closed without merging**
